# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: |
      JGFWebAPI.Bussiness/JGFWebAPI.Bussiness.csproj
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: 'JGFWebAPI.Bussiness/JGFWebAPI.Bussiness.csproj'
    nobuild: true
    versioningScheme: 'off'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '40b7c599-c51c-48ce-bd63-2086c888714e/5b0242aa-2dc9-41b5-898f-53ef818fee1a'
    allowPackageConflicts: true